@startuml

!theme plain
top to bottom direction
skinparam linetype ortho

class call_graph_input {
   call_graph: jsonb
   commit_hash: varchar(255)
   created_at: timestamp(6)
   version: varchar(255)
   project_id: bigint
   id: bigint
}
class call_graph_output {
   changed_call_graph: jsonb
   created_at: timestamp(6)
   source_call_graph_input: jsonb
   target_call_graph_input: jsonb
   project_id: bigint
   id: bigint
}
class changed_context_map {
   changed_links: jsonb
   created_at: timestamp(6)
   context_map_id: bigint
   id: bigint
}
class changed_sdg {
   changed_links: jsonb
   created_at: timestamp(6)
   service_dependency_graph_id: bigint
   id: bigint
}
class context_map {
   commit_hash: varchar(255)
   context_map: jsonb
   created_at: timestamp(6)
   version: varchar(255)
   project_id: bigint
   id: bigint
}
class project {
   created_at: timestamp(6)
   project_name: varchar(255)
   id: bigint
}
class service_dependency_graph {
   commit_hash: varchar(255)
   created_at: timestamp(6)
   service_dependency_graph: jsonb
   version: varchar(255)
   project_id: bigint
   id: bigint
}

call_graph_input          -[#595959,plain]-^  project                  : "project_id:id"
call_graph_output         -[#595959,plain]-^  project                  : "project_id:id"
changed_context_map       -[#595959,plain]-^  context_map              : "context_map_id:id"
changed_sdg               -[#595959,plain]-^  service_dependency_graph : "service_dependency_graph_id:id"
context_map               -[#595959,plain]-^  project                  : "project_id:id"
service_dependency_graph  -[#595959,plain]-^  project                  : "project_id:id"
@enduml
